### ISSUE TITLE
jimmy: openCV calibration + static example

### ISSUE THREAD

**Issue by carlstand** [carlstand/ROS_iiwa_Demo#6]
having a standard way to calibrate the camera and have a example to tracking objects

**Comment by carlstand** [comment]
planning to create a vision station service, runs on ubuntu side,
connection test can start with the client node on RosJava side

**Comment by jm0118** [comment]
a first version of vision station is checked in.

**Comment by jm0118** [comment]
a demo is available, which includes getting target position offset and move the robot by the offset.
